#!/usr/bin/env bash
# configures an Nginx server to have a custom 404 page that contains the string 'Ceci n'est pas une page'

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo '4-not_found_page_404' | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
